In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Amazonbookreviews.csv')

In [3]:
df.head()

,reviewerID,asin,reviewername,helpful,reviewerText,overallRating,Summary,UnixreviewTime,reviewTime
0,A2SUAM1J3GNN3B,23456.0,SNEHA,2,I bought this for my husband who plays the pia...,4.0,SUBWAY SURF,NaN,NaN
1,A2SUAN1J3GNN0C,879877.0,KARTHII,3,good book to read,3.0,PILOT,NaN,NaN
2,A2SUAN1J3GNN7B,23456.0,SHASHANK,3,high cost,2.5,DRIVE IN HEAVEN,NaN,NaN
3,A5SUAN1J3GNN9B,67578.0,NITIN,3,good useof book,2.2,SPORTS HEAVEN,NaN,NaN
4,A1SUAM1J3GNN3B,123.0,PRANOTI,3,I m happy with the book,3.0,HEAVEN OF PEARLS,NaN,NaN

In [7]:
df.shape

(45, 9)

In [5]:
df.columns

Index(['reviewerID', 'asin', 'reviewername', 'helpful', 'reviewerText',
       'overallRating', 'Summary', 'UnixreviewTime', 'reviewTime'],
      dtype='object')

In [6]:
df1 = df[['reviewerID','reviewerID','overallRating']]
df1

         reviewerID       reviewerID  overallRating
0    A2SUAM1J3GNN3B   A2SUAM1J3GNN3B            4.0
1    A2SUAN1J3GNN0C   A2SUAN1J3GNN0C            3.0
2    A2SUAN1J3GNN7B   A2SUAN1J3GNN7B            2.5
3    A5SUAN1J3GNN9B   A5SUAN1J3GNN9B            2.2
4    A1SUAM1J3GNN3B   A1SUAM1J3GNN3B            3.0
5   BA2345WERSDFRER  BA2345WERSDFRER            3.0
6   CADERVG3450EREW  CADERVG3450EREW            3.0
7   ASDF345671QWERT  ASDF345671QWERT            3.0
8     MNHJ879WERFGH    MNHJ879WERFGH            3.0
9    1234ZSDFREQWEG   1234ZSDFREQWEG            5.0
10   9345GHIKLFLLED   9345GHIKLFLLED            4.0
11              NaN              NaN            4.0
12   HGKIUYE345SFDG   HGKIUYE345SFDG            4.0
13  NIKRT2398701222  NIKRT2398701222            3.0
14   MAHI2348900122   MAHI2348900122            3.0
15   LIHJKD87634O21   LIHJKD87634O21            3.0
16  SISISWER4657893  SISISWER4657893            3.0
17   MIKI23412341QW   MIKI23412341QW            2.0
18   AAAJI37DFG378I   AAAJI37DFG378I            2.0
19   FAJI234GAJI987   FAJI234GAJI987            2.0
20    VABI9876ERTT1    VABI9876ERTT1            2.0
21   NIKI12NIKI1231   NIKI12NIKI1231            4.0
22   MIKISDF1232XAD   MIKISDF1232XAD            4.0
23     GHAU8768QWER     GHAU8768QWER            4.0
24   NIKI12NIKI1231   NIKI12NIKI1231            4.0
25   MIKISDF1232XAD   MIKISDF1232XAD            4.0
26     GHAU8768QWER     GHAU8768QWER            4.0
27  BA2345WERSDFRER  BA2345WERSDFRER            4.0
28  CADERVG3450EREW  CADERVG3450EREW            4.0
29  ASDF345671QWERT  ASDF345671QWERT            4.0
30    MNHJ879WERFGH    MNHJ879WERFGH            4.0
31   1234ZSDFREQWEG   1234ZSDFREQWEG            4.0
32   9345GHIKLFLLED   9345GHIKLFLLED            3.0
33              NaN              NaN            3.0
34   HGKIUYE345SFDG   HGKIUYE345SFDG            3.0
35  NIKRT2398701222  NIKRT2398701222            3.0
36   MAHI2348900122   MAHI2348900122            2.0
37   LIHJKD87634O21   LIHJKD87634O21            2.0
38  SISISWER4657893  SISISWER4657893            2.0
39     8786112GHAUI     8786112GHAUI            2.0
40      67FDASAA123      67FDASAA123            4.0
41        ASWER1234        ASWER1234            4.0
42       QWCVFED123       QWCVFED123            4.0
43      123LKIUHNFG      123LKIUHNFG            4.0
44     987DFHGJI657     987DFHGJI657            4.0

In [8]:
df2 = df[['asin','reviewername',]]
df2

        asin reviewername
0    23456.0        SNEHA
1   879877.0      KARTHII
2    23456.0     SHASHANK
3    67578.0        NITIN
4      123.0      PRANOTI
5   236789.0      SHALINI
6        NaN       SNEHAL
7   224442.0       SHIKHA
8    98767.0       AKSHAY
9    78761.0       SATISH
10  321456.0         RAJU
11  876231.0        ROHIT
12     987.0        MOHIT
13     234.0       NILESH
14     124.0      KAILASH
15     156.0        SONAM
16     876.0       RAJESH
17     123.0       SALMAN
18     987.0       PANKAJ
19   22456.0        DIPTI
20    9876.0       MANISH
21    3451.0       SHREYA
22     879.0    AISHWARYA
23     321.0       SUMEET
24       2.0      PRAJWAL
25       1.0        JACOB
26      23.0       MARYLS
27      11.0        CHRIS
28      11.0       MORRIS
29      23.0        HARRY
30   21221.0         JOHN
31      21.0       VARSHA
32   12212.0     SHRADDHA
33    2121.0         SAIF
34   21212.0       KRISSH
35   21221.0         NEIL
36   22245.0      KANGANA
37     678.0        KHANN
38     111.0        RIYAA
39     223.0          NaN
40    2312.0      NANAJJI
41    1222.0       PREETI
42   11111.0        DHONI
43    9800.0         MAHI
44       NaN          DDE

In [9]:
merging = pd.concat([df1,df2], axis=1)
merging

         reviewerID       reviewerID  overallRating      asin reviewername
0    A2SUAM1J3GNN3B   A2SUAM1J3GNN3B            4.0   23456.0        SNEHA
1    A2SUAN1J3GNN0C   A2SUAN1J3GNN0C            3.0  879877.0      KARTHII
2    A2SUAN1J3GNN7B   A2SUAN1J3GNN7B            2.5   23456.0     SHASHANK
3    A5SUAN1J3GNN9B   A5SUAN1J3GNN9B            2.2   67578.0        NITIN
4    A1SUAM1J3GNN3B   A1SUAM1J3GNN3B            3.0     123.0      PRANOTI
5   BA2345WERSDFRER  BA2345WERSDFRER            3.0  236789.0      SHALINI
6   CADERVG3450EREW  CADERVG3450EREW            3.0       NaN       SNEHAL
7   ASDF345671QWERT  ASDF345671QWERT            3.0  224442.0       SHIKHA
8     MNHJ879WERFGH    MNHJ879WERFGH            3.0   98767.0       AKSHAY
9    1234ZSDFREQWEG   1234ZSDFREQWEG            5.0   78761.0       SATISH
10   9345GHIKLFLLED   9345GHIKLFLLED            4.0  321456.0         RAJU
11              NaN              NaN            4.0  876231.0        ROHIT
12   HGKIUYE345SFDG   HGKIUYE345SFDG            4.0     987.0        MOHIT
13  NIKRT2398701222  NIKRT2398701222            3.0     234.0       NILESH
14   MAHI2348900122   MAHI2348900122            3.0     124.0      KAILASH
15   LIHJKD87634O21   LIHJKD87634O21            3.0     156.0        SONAM
16  SISISWER4657893  SISISWER4657893            3.0     876.0       RAJESH
17   MIKI23412341QW   MIKI23412341QW            2.0     123.0       SALMAN
18   AAAJI37DFG378I   AAAJI37DFG378I            2.0     987.0       PANKAJ
19   FAJI234GAJI987   FAJI234GAJI987            2.0   22456.0        DIPTI
20    VABI9876ERTT1    VABI9876ERTT1            2.0    9876.0       MANISH
21   NIKI12NIKI1231   NIKI12NIKI1231            4.0    3451.0       SHREYA
22   MIKISDF1232XAD   MIKISDF1232XAD            4.0     879.0    AISHWARYA
23     GHAU8768QWER     GHAU8768QWER            4.0     321.0       SUMEET
24   NIKI12NIKI1231   NIKI12NIKI1231            4.0       2.0      PRAJWAL
25   MIKISDF1232XAD   MIKISDF1232XAD            4.0       1.0        JACOB
26     GHAU8768QWER     GHAU8768QWER            4.0      23.0       MARYLS
27  BA2345WERSDFRER  BA2345WERSDFRER            4.0      11.0        CHRIS
28  CADERVG3450EREW  CADERVG3450EREW            4.0      11.0       MORRIS
29  ASDF345671QWERT  ASDF345671QWERT            4.0      23.0        HARRY
30    MNHJ879WERFGH    MNHJ879WERFGH            4.0   21221.0         JOHN
31   1234ZSDFREQWEG   1234ZSDFREQWEG            4.0      21.0       VARSHA
32   9345GHIKLFLLED   9345GHIKLFLLED            3.0   12212.0     SHRADDHA
33              NaN              NaN            3.0    2121.0         SAIF
34   HGKIUYE345SFDG   HGKIUYE345SFDG            3.0   21212.0       KRISSH
35  NIKRT2398701222  NIKRT2398701222            3.0   21221.0         NEIL
36   MAHI2348900122   MAHI2348900122            2.0   22245.0      KANGANA
37   LIHJKD87634O21   LIHJKD87634O21            2.0     678.0        KHANN
38  SISISWER4657893  SISISWER4657893            2.0     111.0        RIYAA
39     8786112GHAUI     8786112GHAUI            2.0     223.0          NaN
40      67FDASAA123      67FDASAA123            4.0    2312.0      NANAJJI
41        ASWER1234        ASWER1234            4.0    1222.0       PREETI
42       QWCVFED123       QWCVFED123            4.0   11111.0        DHONI
43      123LKIUHNFG      123LKIUHNFG            4.0    9800.0         MAHI
44     987DFHGJI657     987DFHGJI657            4.0       NaN          DDE

In [11]:
sorting = merging.sort_values('overallRating', ascending=False)
sorting

         reviewerID       reviewerID  overallRating      asin reviewername
9    1234ZSDFREQWEG   1234ZSDFREQWEG            5.0   78761.0       SATISH
0    A2SUAM1J3GNN3B   A2SUAM1J3GNN3B            4.0   23456.0        SNEHA
21   NIKI12NIKI1231   NIKI12NIKI1231            4.0    3451.0       SHREYA
43      123LKIUHNFG      123LKIUHNFG            4.0    9800.0         MAHI
42       QWCVFED123       QWCVFED123            4.0   11111.0        DHONI
41        ASWER1234        ASWER1234            4.0    1222.0       PREETI
40      67FDASAA123      67FDASAA123            4.0    2312.0      NANAJJI
31   1234ZSDFREQWEG   1234ZSDFREQWEG            4.0      21.0       VARSHA
30    MNHJ879WERFGH    MNHJ879WERFGH            4.0   21221.0         JOHN
29  ASDF345671QWERT  ASDF345671QWERT            4.0      23.0        HARRY
28  CADERVG3450EREW  CADERVG3450EREW            4.0      11.0       MORRIS
27  BA2345WERSDFRER  BA2345WERSDFRER            4.0      11.0        CHRIS
26     GHAU8768QWER     GHAU8768QWER            4.0      23.0       MARYLS
25   MIKISDF1232XAD   MIKISDF1232XAD            4.0       1.0        JACOB
24   NIKI12NIKI1231   NIKI12NIKI1231            4.0       2.0      PRAJWAL
23     GHAU8768QWER     GHAU8768QWER            4.0     321.0       SUMEET
22   MIKISDF1232XAD   MIKISDF1232XAD            4.0     879.0    AISHWARYA
44     987DFHGJI657     987DFHGJI657            4.0       NaN          DDE
12   HGKIUYE345SFDG   HGKIUYE345SFDG            4.0     987.0        MOHIT
11              NaN              NaN            4.0  876231.0        ROHIT
10   9345GHIKLFLLED   9345GHIKLFLLED            4.0  321456.0         RAJU
8     MNHJ879WERFGH    MNHJ879WERFGH            3.0   98767.0       AKSHAY
4    A1SUAM1J3GNN3B   A1SUAM1J3GNN3B            3.0     123.0      PRANOTI
5   BA2345WERSDFRER  BA2345WERSDFRER            3.0  236789.0      SHALINI
35  NIKRT2398701222  NIKRT2398701222            3.0   21221.0         NEIL
34   HGKIUYE345SFDG   HGKIUYE345SFDG            3.0   21212.0       KRISSH
33              NaN              NaN            3.0    2121.0         SAIF
32   9345GHIKLFLLED   9345GHIKLFLLED            3.0   12212.0     SHRADDHA
7   ASDF345671QWERT  ASDF345671QWERT            3.0  224442.0       SHIKHA
6   CADERVG3450EREW  CADERVG3450EREW            3.0       NaN       SNEHAL
13  NIKRT2398701222  NIKRT2398701222            3.0     234.0       NILESH
14   MAHI2348900122   MAHI2348900122            3.0     124.0      KAILASH
15   LIHJKD87634O21   LIHJKD87634O21            3.0     156.0        SONAM
1    A2SUAN1J3GNN0C   A2SUAN1J3GNN0C            3.0  879877.0      KARTHII
16  SISISWER4657893  SISISWER4657893            3.0     876.0       RAJESH
2    A2SUAN1J3GNN7B   A2SUAN1J3GNN7B            2.5   23456.0     SHASHANK
3    A5SUAN1J3GNN9B   A5SUAN1J3GNN9B            2.2   67578.0        NITIN
18   AAAJI37DFG378I   AAAJI37DFG378I            2.0     987.0       PANKAJ
36   MAHI2348900122   MAHI2348900122            2.0   22245.0      KANGANA
37   LIHJKD87634O21   LIHJKD87634O21            2.0     678.0        KHANN
38  SISISWER4657893  SISISWER4657893            2.0     111.0        RIYAA
39     8786112GHAUI     8786112GHAUI            2.0     223.0          NaN
20    VABI9876ERTT1    VABI9876ERTT1            2.0    9876.0       MANISH
19   FAJI234GAJI987   FAJI234GAJI987            2.0   22456.0        DIPTI
17   MIKI23412341QW   MIKI23412341QW            2.0     123.0       SALMAN

In [12]:
sorting.transpose()

,9,0,21,43,42,41,40,31,30,29,...,2,3,18,36,37,38,39,20,19,17
reviewerID,1234ZSDFREQWEG,A2SUAM1J3GNN3B,NIKI12NIKI1231,123LKIUHNFG,QWCVFED123,ASWER1234,67FDASAA123,1234ZSDFREQWEG,MNHJ879WERFGH,ASDF345671QWERT,...,A2SUAN1J3GNN7B,A5SUAN1J3GNN9B,AAAJI37DFG378I,MAHI2348900122,LIHJKD87634O21,SISISWER4657893,8786112GHAUI,VABI9876ERTT1,FAJI234GAJI987,MIKI23412341QW
reviewerID,1234ZSDFREQWEG,A2SUAM1J3GNN3B,NIKI12NIKI1231,123LKIUHNFG,QWCVFED123,ASWER1234,67FDASAA123,1234ZSDFREQWEG,MNHJ879WERFGH,ASDF345671QWERT,...,A2SUAN1J3GNN7B,A5SUAN1J3GNN9B,AAAJI37DFG378I,MAHI2348900122,LIHJKD87634O21,SISISWER4657893,8786112GHAUI,VABI9876ERTT1,FAJI234GAJI987,MIKI23412341QW
overallRating,5,4,4,4,4,4,4,4,4,4,...,2.5,2.2,2,2,2,2,2,2,2,2
asin,78761,23456,3451,9800,11111,1222,2312,21,21221,23,...,23456,67578,987,22245,678,111,223,9876,22456,123
reviewername,SATISH,SNEHA,SHREYA,MAHI,DHONI,PREETI,NANAJJI,VARSHA,JOHN,HARRY,...,SHASHANK,NITIN,PANKAJ,KANGANA,KHANN,RIYAA,NaN,MANISH,DIPTI,SALMAN

In [13]:
sorting.shape

(45, 5)

In [14]:
array = sorting.values
reshaped_array = np.reshape(array,(5,45))
reshaped_array

array([['1234ZSDFREQWEG', '1234ZSDFREQWEG', 5.0, 78761.0, 'SATISH',
        'A2SUAM1J3GNN3B', 'A2SUAM1J3GNN3B', 4.0, 23456.0, 'SNEHA',
        'NIKI12NIKI1231', 'NIKI12NIKI1231', 4.0, 3451.0, 'SHREYA',
        '123LKIUHNFG', '123LKIUHNFG', 4.0, 9800.0, 'MAHI', 'QWCVFED123',
        'QWCVFED123', 4.0, 11111.0, 'DHONI', 'ASWER1234', 'ASWER1234',
        4.0, 1222.0, 'PREETI', '67FDASAA123', '67FDASAA123', 4.0, 2312.0,
        'NANAJJI', '1234ZSDFREQWEG', '1234ZSDFREQWEG', 4.0, 21.0,
        'VARSHA', 'MNHJ879WERFGH', 'MNHJ879WERFGH', 4.0, 21221.0, 'JOHN'],
       ['ASDF345671QWERT', 'ASDF345671QWERT', 4.0, 23.0, 'HARRY',
        'CADERVG3450EREW', 'CADERVG3450EREW', 4.0, 11.0, 'MORRIS',
        'BA2345WERSDFRER', 'BA2345WERSDFRER', 4.0, 11.0, 'CHRIS',
        'GHAU8768QWER', 'GHAU8768QWER', 4.0, 23.0, 'MARYLS',
        'MIKISDF1232XAD', 'MIKISDF1232XAD', 4.0, 1.0, 'JACOB',
        'NIKI12NIKI1231', 'NIKI12NIKI1231', 4.0, 2.0, 'PRAJWAL',
        'GHAU8768QWER', 'GHAU8768QWER', 4.0, 321.0, 'SUMEET',
        'MIKISDF1232XAD', 'MIKISDF1232XAD', 4.0, 879.0, 'AISHWARYA',
        '987DFHGJI657', '987DFHGJI657', 4.0, nan, 'DDE'],
       ['HGKIUYE345SFDG', 'HGKIUYE345SFDG', 4.0, 987.0, 'MOHIT', nan,
        nan, 4.0, 876231.0, 'ROHIT', '9345GHIKLFLLED', '9345GHIKLFLLED',
        4.0, 321456.0, 'RAJU', 'MNHJ879WERFGH', 'MNHJ879WERFGH', 3.0,
        98767.0, 'AKSHAY', 'A1SUAM1J3GNN3B', 'A1SUAM1J3GNN3B', 3.0,
        123.0, 'PRANOTI', 'BA2345WERSDFRER', 'BA2345WERSDFRER', 3.0,
        236789.0, 'SHALINI', 'NIKRT2398701222', 'NIKRT2398701222', 3.0,
        21221.0, 'NEIL', 'HGKIUYE345SFDG', 'HGKIUYE345SFDG', 3.0,
        21212.0, 'KRISSH', nan, nan, 3.0, 2121.0, 'SAIF'],
       ['9345GHIKLFLLED', '9345GHIKLFLLED', 3.0, 12212.0, 'SHRADDHA',
        'ASDF345671QWERT', 'ASDF345671QWERT', 3.0, 224442.0, 'SHIKHA',
        'CADERVG3450EREW', 'CADERVG3450EREW', 3.0, nan, 'SNEHAL',
        'NIKRT2398701222', 'NIKRT2398701222', 3.0, 234.0, 'NILESH',
        'MAHI2348900122', 'MAHI2348900122', 3.0, 124.0, 'KAILASH',
        'LIHJKD87634O21', 'LIHJKD87634O21', 3.0, 156.0, 'SONAM',
        'A2SUAN1J3GNN0C', 'A2SUAN1J3GNN0C', 3.0, 879877.0, 'KARTHII',
        'SISISWER4657893', 'SISISWER4657893', 3.0, 876.0, 'RAJESH',
        'A2SUAN1J3GNN7B', 'A2SUAN1J3GNN7B', 2.5, 23456.0, 'SHASHANK'],
       ['A5SUAN1J3GNN9B', 'A5SUAN1J3GNN9B', 2.2, 67578.0, 'NITIN',
        'AAAJI37DFG378I', 'AAAJI37DFG378I', 2.0, 987.0, 'PANKAJ',
        'MAHI2348900122', 'MAHI2348900122', 2.0, 22245.0, 'KANGANA',
        'LIHJKD87634O21', 'LIHJKD87634O21', 2.0, 678.0, 'KHANN',
        'SISISWER4657893', 'SISISWER4657893', 2.0, 111.0, 'RIYAA',
        '8786112GHAUI', '8786112GHAUI', 2.0, 223.0, nan, 'VABI9876ERTT1',
        'VABI9876ERTT1', 2.0, 9876.0, 'MANISH', 'FAJI234GAJI987',
        'FAJI234GAJI987', 2.0, 22456.0, 'DIPTI', 'MIKI23412341QW',
        'MIKI23412341QW', 2.0, 123.0, 'SALMAN']], dtype=object)