In [28]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Amazonbookreviews.csv')

In [3]:
df.head()

,reviewerID,asin,reviewername,helpful,reviewerText,overallRating,Summary,UnixreviewTime,reviewTime
0,A2SUAM1J3GNN3B,23456.0,SNEHA,2,I bought this for my husband who plays the pia...,4.0,SUBWAY SURF,NaN,NaN
1,A2SUAN1J3GNN0C,879877.0,KARTHII,3,good book to read,3.0,PILOT,NaN,NaN
2,A2SUAN1J3GNN7B,23456.0,SHASHANK,3,high cost,2.5,DRIVE IN HEAVEN,NaN,NaN
3,A5SUAN1J3GNN9B,67578.0,NITIN,3,good useof book,2.2,SPORTS HEAVEN,NaN,NaN
4,A1SUAM1J3GNN3B,123.0,PRANOTI,3,I m happy with the book,3.0,HEAVEN OF PEARLS,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 9 columns):
reviewerID        43 non-null object
asin              43 non-null float64
reviewername      44 non-null object
helpful           45 non-null int64
reviewerText      45 non-null object
overallRating     45 non-null float64
Summary           45 non-null object
UnixreviewTime    0 non-null float64
reviewTime        0 non-null float64
dtypes: float64(4), int64(1), object(4)
memory usage: 2.5+ KB

In [6]:
df.shape

(45, 9)

In [7]:
df.columns

Index(['reviewerID', 'asin', 'reviewername', 'helpful', 'reviewerText',
       'overallRating', 'Summary', 'UnixreviewTime', 'reviewTime'],
      dtype='object')

In [19]:
#creating subsets
df1 = df[['reviewerID','helpful','overallRating']].iloc[:11]
df1

         reviewerID  helpful  overallRating
0    A2SUAM1J3GNN3B        2            4.0
1    A2SUAN1J3GNN0C        3            3.0
2    A2SUAN1J3GNN7B        3            2.5
3    A5SUAN1J3GNN9B        3            2.2
4    A1SUAM1J3GNN3B        3            3.0
5   BA2345WERSDFRER        3            3.0
6   CADERVG3450EREW        3            3.0
7   ASDF345671QWERT        3            3.0
8     MNHJ879WERFGH        2            3.0
9    1234ZSDFREQWEG        2            5.0
10   9345GHIKLFLLED        2            4.0

In [20]:
df2 = df[['reviewerID','helpful','overallRating']].iloc[11:21]
df2

         reviewerID  helpful  overallRating
11              NaN        2            4.0
12   HGKIUYE345SFDG        2            4.0
13  NIKRT2398701222        2            3.0
14   MAHI2348900122        2            3.0
15   LIHJKD87634O21        2            3.0
16  SISISWER4657893        2            3.0
17   MIKI23412341QW        2            2.0
18   AAAJI37DFG378I        2            2.0
19   FAJI234GAJI987        2            2.0
20    VABI9876ERTT1        2            2.0

In [21]:
df3 = df[['reviewerID','helpful','overallRating']].iloc[21:31]
df3

         reviewerID  helpful  overallRating
21   NIKI12NIKI1231        2            4.0
22   MIKISDF1232XAD        2            4.0
23     GHAU8768QWER        2            4.0
24   NIKI12NIKI1231        3            4.0
25   MIKISDF1232XAD        3            4.0
26     GHAU8768QWER        3            4.0
27  BA2345WERSDFRER        3            4.0
28  CADERVG3450EREW        3            4.0
29  ASDF345671QWERT        3            4.0
30    MNHJ879WERFGH        3            4.0

In [22]:
merging = pd.concat([df1,df2,df3])
merging

         reviewerID  helpful  overallRating
0    A2SUAM1J3GNN3B        2            4.0
1    A2SUAN1J3GNN0C        3            3.0
2    A2SUAN1J3GNN7B        3            2.5
3    A5SUAN1J3GNN9B        3            2.2
4    A1SUAM1J3GNN3B        3            3.0
5   BA2345WERSDFRER        3            3.0
6   CADERVG3450EREW        3            3.0
7   ASDF345671QWERT        3            3.0
8     MNHJ879WERFGH        2            3.0
9    1234ZSDFREQWEG        2            5.0
10   9345GHIKLFLLED        2            4.0
11              NaN        2            4.0
12   HGKIUYE345SFDG        2            4.0
13  NIKRT2398701222        2            3.0
14   MAHI2348900122        2            3.0
15   LIHJKD87634O21        2            3.0
16  SISISWER4657893        2            3.0
17   MIKI23412341QW        2            2.0
18   AAAJI37DFG378I        2            2.0
19   FAJI234GAJI987        2            2.0
20    VABI9876ERTT1        2            2.0
21   NIKI12NIKI1231        2            4.0
22   MIKISDF1232XAD        2            4.0
23     GHAU8768QWER        2            4.0
24   NIKI12NIKI1231        3            4.0
25   MIKISDF1232XAD        3            4.0
26     GHAU8768QWER        3            4.0
27  BA2345WERSDFRER        3            4.0
28  CADERVG3450EREW        3            4.0
29  ASDF345671QWERT        3            4.0
30    MNHJ879WERFGH        3            4.0

In [24]:
sorting = merging.sort_values('overallRating', ascending=False)
sorting

         reviewerID  helpful  overallRating
9    1234ZSDFREQWEG        2            5.0
0    A2SUAM1J3GNN3B        2            4.0
12   HGKIUYE345SFDG        2            4.0
29  ASDF345671QWERT        3            4.0
28  CADERVG3450EREW        3            4.0
27  BA2345WERSDFRER        3            4.0
26     GHAU8768QWER        3            4.0
25   MIKISDF1232XAD        3            4.0
24   NIKI12NIKI1231        3            4.0
23     GHAU8768QWER        2            4.0
22   MIKISDF1232XAD        2            4.0
21   NIKI12NIKI1231        2            4.0
30    MNHJ879WERFGH        3            4.0
10   9345GHIKLFLLED        2            4.0
11              NaN        2            4.0
4    A1SUAM1J3GNN3B        3            3.0
5   BA2345WERSDFRER        3            3.0
6   CADERVG3450EREW        3            3.0
7   ASDF345671QWERT        3            3.0
8     MNHJ879WERFGH        2            3.0
14   MAHI2348900122        2            3.0
13  NIKRT2398701222        2            3.0
16  SISISWER4657893        2            3.0
1    A2SUAN1J3GNN0C        3            3.0
15   LIHJKD87634O21        2            3.0
2    A2SUAN1J3GNN7B        3            2.5
3    A5SUAN1J3GNN9B        3            2.2
20    VABI9876ERTT1        2            2.0
19   FAJI234GAJI987        2            2.0
18   AAAJI37DFG378I        2            2.0
17   MIKI23412341QW        2            2.0

In [25]:
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,35,36,37,38,39,40,41,42,43,44
reviewerID,A2SUAM1J3GNN3B,A2SUAN1J3GNN0C,A2SUAN1J3GNN7B,A5SUAN1J3GNN9B,A1SUAM1J3GNN3B,BA2345WERSDFRER,CADERVG3450EREW,ASDF345671QWERT,MNHJ879WERFGH,1234ZSDFREQWEG,...,NIKRT2398701222,MAHI2348900122,LIHJKD87634O21,SISISWER4657893,8786112GHAUI,67FDASAA123,ASWER1234,QWCVFED123,123LKIUHNFG,987DFHGJI657
asin,23456,879877,23456,67578,123,236789,NaN,224442,98767,78761,...,21221,22245,678,111,223,2312,1222,11111,9800,NaN
reviewername,SNEHA,KARTHII,SHASHANK,NITIN,PRANOTI,SHALINI,SNEHAL,SHIKHA,AKSHAY,SATISH,...,NEIL,KANGANA,KHANN,RIYAA,NaN,NANAJJI,PREETI,DHONI,MAHI,DDE
helpful,2,3,3,3,3,3,3,3,2,2,...,3,3,3,3,3,3,2,2,2,2
reviewerText,I bought this for my husband who plays the pia...,good book to read,high cost,good useof book,I m happy with the book,im not happy with the delay of product,delay in book,Wonderful book,The music is at times hard to read because we ...,many errors,...,8.78E+21,67667,3434567,098O,GOOD LUCK,BYE MY LOVE,LOVE U,HELLO DEAR,DAER PLEASE READ BOOK,BOOK
overallRating,4,3,2.5,2.2,3,3,3,3,3,5,...,3,2,2,2,2,4,4,4,4,4
Summary,SUBWAY SURF,PILOT,DRIVE IN HEAVEN,SPORTS HEAVEN,HEAVEN OF PEARLS,GODS GIFT,GODESS LIFE,LIFE OF PIE,INDIA A MASSIVE POWER,DATA IS DATA,...,good buy for money,money is dis,stare the raeder,reader is giood,faskjas,HELL OF HELL,DEAA,DEAR TO ALL,MOTHER,WINE OF WINE
UnixreviewTime,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reviewTime,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
merging.transpose()

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
reviewerID,A2SUAM1J3GNN3B,A2SUAN1J3GNN0C,A2SUAN1J3GNN7B,A5SUAN1J3GNN9B,A1SUAM1J3GNN3B,BA2345WERSDFRER,CADERVG3450EREW,ASDF345671QWERT,MNHJ879WERFGH,1234ZSDFREQWEG,...,NIKI12NIKI1231,MIKISDF1232XAD,GHAU8768QWER,NIKI12NIKI1231,MIKISDF1232XAD,GHAU8768QWER,BA2345WERSDFRER,CADERVG3450EREW,ASDF345671QWERT,MNHJ879WERFGH
helpful,2,3,3,3,3,3,3,3,2,2,...,2,2,2,3,3,3,3,3,3,3
overallRating,4,3,2.5,2.2,3,3,3,3,3,5,...,4,4,4,4,4,4,4,4,4,4

In [38]:
sorting.shape

(31, 3)

In [35]:
array = sorting.values
reshaped_array = np.reshape(array, (3, 31))